### ISSUE TITLE
issues with Guild Create 

### ISSUE THREAD

**Issue by TheTeaCup** [TritaxGamer/Tritax-Bot-v1.5#3]
Origanal 
bot.on('guildCreate', guild => {
  
        let joinLogs = guild.channels.find(`name`, 'logs');
      const embed = new Discord.RichEmbed()
      .setColor(0x00AE86)
      .setAuthor(`Joined ${guild.name}`)
      .setThumbnail(guild.iconURL)
      .addField("Owner", guild.owner)
      .addField("ID", guild.id, true)
      .addField("Users", guild.memberCount, true)
      .addField("Channels", guild.channels.size, true)
      joinLogs.send(embed);
        });

I'm getting the error   
 joinLogs.send(embed);
               ^

TypeError: Cannot read property 'send' of null
    at Client.bot.on.guild (C:\Users\lw048\Desktop\logan\index.js:307:16)
    at Client.emit (events.js:160:13)
    at ClientDataManager.newGuild (C:\Users\lw048\Desktop\logan\node_modules\discord.js\src\client\ClientDataManager.js:35:21)
    at GuildCreateHandler.handle (C:\Users\lw048\Desktop\logan\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:17:26)
    at WebSocketPacketManager.handle (C:\Users\lw048\Desktop\logan\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\lw048\Desktop\logan\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\lw048\Desktop\logan\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\lw048\Desktop\logan\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:160:13)
    at Receiver._receiver.onmessage (C:\Users\lw048\Desktop\logan\node_modules\ws\lib\websocket.js:145:47)`

**Comment by bhavya-dang** [comment]
Oh thats because you dont have a logs channel. I will just make this event  @HunterWilson56 in my  guild only.
